### ISSUE TITLE
Suggestion: Make the Arrows less stingy on how they work.

### ISSUE THREAD

**Issue by Greg727** [Hydraheads/RoundaboutMod#1]
Both the Stand and Worthiness arrows only work if they are shot from a bow or crossbow. I think it would be easier if they also work if the player hits a mob with them with while the arrows are in the players hands.

**Comment by ErrorFYM** [comment]
You can give an arrow to stand (using Shift + X while holding an arrow) and make him throw it.

**Comment by Hydraheads** [comment]
This is not an issue, this is a design choice to make you use bows or crossbows like in the anime. The reference would kind of be lost if people were incentivized to just whack people with arrows.
