### ISSUE TITLE
[BUG?] Stands can be effected with potions

### ISSUE THREAD

**Issue by HyperMan19680** [Hydraheads/RoundaboutMod#2]
I use the Everlasting Abilities Mod alongside this mod, with gives semi-perm potions effects to you and others nearby, depending on the type of potion, and the problem I have is it is effecting my Stand with negative potion effects like Weakness and Bad Luck. Can we possibly get immunity to the Stands for Potion effects of all kinds?

**Comment by Hydraheads** [comment]
There is a line of code on stand entities called  public boolean isAffectedByPotions() {return false;}
This is a vanilla function, and it makes mobs unable to be given potion effects. So it sounds like that mod is ignoring a vanilla function that hard blacklists mobs from being affected by potions. Tell the mod author of everlasting abilities to add compatibility to vanilla and direct them to that function.

**Comment by HyperMan19680** [comment]
I did a little testing after posting and while it looks like Stands aren't directly effected, they still appear on the Stand NPC when using a way to see what potion effects are on a mob, like the Neat mod.
